-- Add rewards_generated field to track rewards created by positions (regardless of delegation)
ALTER TABLE staking_positions_by_epoch
ADD COLUMN rewards_generated TEXT NOT NULL DEFAULT '0000000000000000000000000000000000000000000000000000000000000000';

-- Add total_rewards_generated to track lifetime rewards generated by positions owned
ALTER TABLE staking_positions_aggregate
ADD COLUMN total_rewards_generated TEXT NOT NULL DEFAULT '0000000000000000000000000000000000000000000000000000000000000000';

-- Note: total_rewards_earned already exists and tracks rewards actually received
-- This allows us to distinguish between:
-- - total_rewards_generated: rewards created by positions owned by this address
-- - total_rewards_earned: rewards actually received by this address (from own positions or delegations)